POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: beaRer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vbW8iLCJpZCI6IjY1YTI1NThjYjYyOTY0NDBhMWQ2MzYzNCIsImlhdCI6MTcwNTE0MTYyM30.Gj6A0148klpNRAbT3_caW1GminSru_SF3QVvB2yABZA

{
  "title": "bearer again",
  "author": "adamgrant",
  "url": "https://adamgrant.net/"
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "userId": "65a1f414d86766f08ef91023"
}


###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "not found user._id",
  "author": "bombom",
  "url": "https://reactpatterns.com/",
  "userId": "65a1f414d86766f08ef91025"
}